FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]